version: '3.4'
networks:
  default:
    name: SimpleAPI_Docker_Network

services:
  SimpleAPI:
    container_name: SimpleAPI
    image: ${DOCKER_REGISTRY}/simpleapi:dev
    build:
      context: .
      dockerfile: SimpleAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro